name: pytest

permissions:
  checks: write
  pull-requests: write

on:
  pull_request:

jobs:
  pytest:
    name: Run Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1

      - name: Install Dependencies
        working-directory: app/backend
        run: poetry install --no-interaction

      - name: Run Pytest
        working-directory: app/backend
        run: poetry run pytest --junitxml=coverage/pytest.xml --cov-report=term-missing --cov=backend --cov-branch tests/ | tee pytest-coverage.txt
        continue-on-error: true

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./app/backend/coverage/pytest-coverage.txt
          junitxml-path: ./app/backend/coverage/pytest.xml
          hide-badge: false
          hide-report: false